### ISSUE TITLE
Fix stdlib version constraint.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [brettkolodny/gleam-hug#6]
Hug has the current constraint on the standard library:

https://github.com/brettkolodny/gleam-hug/blob/22eb85ef70b33af4cabdb4b0eeca9fbd919cc244/gleam.toml#L12

This means that for many new projects the latest version of hug is unusable: the latest release of the standard library is 0.36.0 The only version of hug that satisfies that constraint is the initial 0.1.0.

It would be really great if hug had the same constraint as all new projects:

```
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
```

which means it would be compatible with any projects created with gleam v1

**Comment by inoas** [comment]
Fixed here https://github.com/brettkolodny/gleam-hug/pull/5/files#diff-7cd1e07e743a743d849d706b1dafd77e5839325c3b7327d3f060335605d525beR12
